USE [master]
GO

/****** Object:  Database [DBTask]    Script Date: 9/13/2020 12:26:34 PM ******/
CREATE DATABASE [DBTask]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBTask', FILENAME = N'E:\Angular\TaskBUE\DBTask.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBTask_log', FILENAME = N'E:\Angular\TaskBUE\DBTask_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBTask].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBTask] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBTask] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBTask] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBTask] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBTask] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBTask] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBTask] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBTask] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBTask] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBTask] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBTask] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBTask] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBTask] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBTask] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBTask] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBTask] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBTask] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBTask] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBTask] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBTask] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBTask] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBTask] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBTask] SET RECOVERY FULL 
GO

ALTER DATABASE [DBTask] SET  MULTI_USER 
GO

ALTER DATABASE [DBTask] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBTask] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBTask] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBTask] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBTask] SET  READ_WRITE 
GO

