// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Web_API
{
    public partial class Employees
    {
        public string FistName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int EmpId { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
    }
}